### ISSUE TITLE
DPI Tunnel

### ISSUE THREAD

**Issue by zhenyolka** [danoctavian/awesome-anti-censorship#8]
Hello! I have an android app called DPI Tunnel. Its used for bypass DPI and get access to locked sites. More simple, its android implementation of GoodbyeDPI. Can you please add it to your list?
Github repo: [DPI Tunnel](https://github.com/zhenyolka/DPITunnel)

**Comment by danoctavian** [comment]
@zhenyolka  thanks i'm taking a look at it!

**Comment by danoctavian** [comment]
added
